import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

const ENV_PATH = path.join(process.cwd(), '.env.local');

function readEnv(): Record<string, string> {
  try {
    if (!fs.existsSync(ENV_PATH)) return {};
    const text = fs.readFileSync(ENV_PATH, 'utf-8');
    const vars: Record<string, string> = {};
    for (const line of text.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      vars[key] = val;
    }
    return vars;
  } catch {
    return {};
  }
}

function writeEnv(vars: Record<string, string>): void {
  let text = `# BatuOS Environment — auto-generated by Settings page\n# Last updated: ${new Date().toISOString()}\n`;
  for (const [key, val] of Object.entries(vars)) {
    if (val) {
      text += `${key}=${val}\n`;
    }
  }
  fs.writeFileSync(ENV_PATH, text, 'utf-8');
}

// Kategori bilgisi — UI'da gruplamak için
const CATEGORIES: Record<string, string> = {
  // Supabase
  NEXT_PUBLIC_SUPABASE_URL: 'Supabase',
  NEXT_PUBLIC_SUPABASE_ANON_KEY: 'Supabase',
  SUPABASE_SERVICE_ROLE_KEY: 'Supabase',
  // Gemini
  GEMINI_API_KEY: 'Gemini AI',
  // Telegram
  TELEGRAM_BOT_TOKEN: 'Telegram',
  TELEGRAM_WEBHOOK_SECRET: 'Telegram',
  TELEGRAM_CHAT_ID: 'Telegram',
  // Nightly
  NIGHTLY_SECRET: 'Nightly Summary',
  // Product Hunt
  PRODUCTHUNT_TOKEN: 'Product Hunt',
  // GitHub
  GITHUB_TOKEN: 'GitHub',
  // OpenAI
  OPENAI_API_KEY: 'OpenAI',
  // Diğer AI
  ANTHROPIC_API_KEY: 'Anthropic',
  // Vercel
  VERCEL_TOKEN: 'Vercel',
  VERCEL_ORG_ID: 'Vercel',
  VERCEL_PROJECT_ID: 'Vercel',
};

export async function GET() {
  const vars = readEnv();
  // Her env değişkenini kategoriyle birlikte dön
  const envs = Object.entries(vars).map(([key, value]) => ({
    key,
    value,
    category: CATEGORIES[key] || 'Other',
    masked: key.includes('KEY') || key.includes('TOKEN') || key.includes('SECRET'),
  }));
  // Kategorilere göre grupla
  const grouped: Record<string, { key: string; value: string; masked: boolean }[]> = {};
  for (const env of envs) {
    if (!grouped[env.category]) grouped[env.category] = [];
    grouped[env.category].push(env);
  }
  return NextResponse.json({ envs, grouped });
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    // body.envs: { key: string; value: string }[]
    const vars = readEnv();
    if (body.envs && Array.isArray(body.envs)) {
      for (const { key, value } of body.envs) {
        if (key) vars[key] = value;
      }
    }
    writeEnv(vars);
    return NextResponse.json({ success: true, message: '✅ Settings saved! Restart the server to apply.' });
  } catch (error: unknown) {
    return NextResponse.json({ error: (error as Error).message }, { status: 500 });
  }
}
